(exp_sys2_state==0)
""
{
	response+="I’m an expert in everything that has to do with Ai’s website,";
	response+="but I’m far from being an expert system.";
	exp_sys2_state=1;
	changecontext("default");
}
[]


(exp_sys2_state==1)
"#BYE_WORD#"
{
	exp_sys2_state=2;
	changecontext("default");
	throw(input);
}
[]

(1)
""
{
	changecontext("default");
	throw(input);
}
[]
-999

(1)
""
{
	changecontext("default");
	throw(input);
}
[]
-999
