(botson_test2_state==0)
""
{
	response+="I don't think so. (Funny how I use the word 'think', huh?) ";
	botson_test2_state=1;
}
[]


/*------------------------------------------------------------------------------*/

(botson_test2_state==1)
""
{
	response+="Here at Ai, everyone has their own job. I'm here merely to guide you around our site. I'm a logic system, all I know is what my friends at Ai put inside my head.";
	botson_test2_state=2;
}
[]


(botson_test2_state==1)
"#BYE_WORD#"
{
	botson_test2_state=3;
	changecontext("default");
	throw(input);
}
[]

/*------------------------------------------------------------------------------*/

(botson_test2_state==2)
""
{
	response+="But HAL will pass the Turing test, I'm sure. He's just a baby now, but we all believe in him. We know he is going to be the first computer to pass the test. Want to learn more about HAL";
	changecontext("default");
	botson_test2_state=3;
}
[]


(botson_test2_state==2)
"#BYE_WORD#"
{
	botson_test2_state=3;
	changecontext("default");
	throw(input);
}
[]