(1)
"(.*)"
RANDOMLOOP
{
	response = "It seems you don't want to give me your name. No problem. What would you like to know about Ai?";
	changecontext("default");
}
{
	response = "That's okay. I don't need to know your name to help you around Ai's site. What would you like to know about Ai?";
	changecontext("default");
}
[]

(1)
""
{
	changecontext("default");
	throw(input);
}
[]

(1)
""
{
	changecontext("default");
	throw(input);
}
[]
